workflow:
    name: Android Application Pipeline
    rules:
        - if: $CI_COMMIT_BRANCH == 'main' || $CI_COMMIT_BRANCH =~ /^feature/
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^feature/ && $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: always

stages:
  - test
  - containerization
  - deploy

variables:
  ANDROID_SDK_ROOT: "/opt/android-sdk"
  ANDROID_HOME: "/opt/android-sdk"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  DOCKER_USERNAME: farahelloumi
  IMAGE_VERSION: $CI_PIPELINE_ID

cache:
  key: gradle-cache
  paths:
    - .gradle/
    - app/.gradle/
    - app/build/

before_script:
  - export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
  - sudo mkdir -p $ANDROID_SDK_ROOT/licenses
  - sudo chmod -R 777 $ANDROID_SDK_ROOT
  - yes | sdkmanager --licenses || true
  - chmod +x gradlew

unit_testing:
  stage: test
  tags:    
    - local
    - aosp
    - linux
  script:
    - ./gradlew test

docker_build:
  stage: containerization
  tags:    
    - local
    - aosp
    - linux
  image: docker:24.0.5
  dependencies: []
  needs:
    - unit_testing
  services:
    - docker:24.0.5-dind
  script:
    - sudo docker build -t $DOCKER_USERNAME/android-build:latest .
    - echo $IMAGE_VERSION
    - sudo docker tag $DOCKER_USERNAME/android-build:latest $DOCKER_USERNAME/android-build:$IMAGE_VERSION
    - sudo docker images $DOCKER_USERNAME/android-build:latest

docker_push:
  stage: containerization
  tags:    
    - local
    - aosp
    - linux
  needs:
    - docker_build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker logout
    - sudo -u gitlab-runner docker login -u "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_PASSWORD"
    - echo "$DOCKER_USERNAME"
    - echo -n "$DOCKER_PASSWORD" | wc -c
    - sudo -u gitlab-runner docker info | grep Username
    - sudo -u gitlab-runner cat /home/gitlab-runner/.docker/config.json
    - sudo docker images | grep "farahelloumi/android-build"
    - sudo -u gitlab-runner docker push farahelloumi/android-build:latest